/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.awt.AWTUtilities;
import com.sun.swing.internal.plaf.basic.resources.basic;
import java.awt.Color;
import java.awt.Shape;
import static java.awt.SystemColor.text;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;
import javax.swing.*; 
import entity.borde;
import java.awt.Font;
import javax.swing.border.Border;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author danie
 */
public class view extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    
    /**
     * Creates new form view
     */
    public view() {
        initComponents();
        
        tableproduct();
    }
    int x=0;
    int y=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jinsertpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbclean = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtinsertname = new javax.swing.JTextField();
        jtinsertmarca = new javax.swing.JTextField();
        jcinsertkind = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jtinsertvent = new javax.swing.JTextField();
        jtinsertnumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbinsertar1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtproductos = new javax.swing.JTable();
        jviewpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtviewname = new javax.swing.JTextField();
        jtviewmarca = new javax.swing.JTextField();
        jccategory = new javax.swing.JComboBox<>();
        jbviewsearch = new javax.swing.JLabel();
        jbviewlistall = new javax.swing.JLabel();
        jbviewclean = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(151, 17, 21));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(151, 17, 21));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("INSERTAR PRODUCTOS");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_product_50px.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 290, 50));

        jPanel5.setBackground(new java.awt.Color(151, 17, 21));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("VER PRODUCTOS");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_list_50px.png"))); // NOI18N
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 290, 50));

        jPanel6.setBackground(new java.awt.Color(151, 17, 21));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("LIMPIAR TABLA");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Trash_50px_1.png"))); // NOI18N
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 290, 50));

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        jinsertpanel.setBackground(new java.awt.Color(217, 32, 36));
        jinsertpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INSERTAR PRODUCTOS");
        jinsertpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MARCA");
        jinsertpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jbclean.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jbclean.setForeground(new java.awt.Color(255, 255, 255));
        jbclean.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbclean.setText("LIMPIAR CAMPOS");
        jbclean.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jbclean.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbcleanMouseMoved(evt);
            }
        });
        jbclean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbcleanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbcleanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbcleanMouseExited(evt);
            }
        });
        jinsertpanel.add(jbclean, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 164, 35));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TIPO");
        jinsertpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 50, -1, -1));

        jtinsertname.setBackground(new Color(0,0,0,0));
        jtinsertname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtinsertname.setForeground(new java.awt.Color(255, 255, 255));
        jtinsertname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtinsertname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jtinsertname.setName(""); // NOI18N
        jtinsertname.setOpaque(false);
        jtinsertname.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtinsertnamePropertyChange(evt);
            }
        });
        jinsertpanel.add(jtinsertname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 207, 38));

        jtinsertmarca.setBackground(new Color(0,0,0,0));
        jtinsertmarca.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtinsertmarca.setForeground(new java.awt.Color(255, 255, 255));
        jtinsertmarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtinsertmarca.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jtinsertmarca.setOpaque(false);
        jinsertpanel.add(jtinsertmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 207, 38));

        jcinsertkind.setBackground(new Color(0,0,0,0));
        jcinsertkind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcinsertkind.setForeground(new java.awt.Color(255, 255, 255));
        jcinsertkind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcinsertkind.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jcinsertkind.setOpaque(false);
        jinsertpanel.add(jcinsertkind, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 188, 38));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PRECIO DE VENTA");
        jinsertpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jtinsertvent.setBackground(new Color(0,0,0,0));
        jtinsertvent.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtinsertvent.setForeground(new java.awt.Color(255, 255, 255));
        jtinsertvent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtinsertvent.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jtinsertvent.setOpaque(false);
        jinsertpanel.add(jtinsertvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 207, 40));

        jtinsertnumber.setBackground(new Color(0,0,0,0));
        jtinsertnumber.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtinsertnumber.setForeground(new java.awt.Color(255, 255, 255));
        jtinsertnumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtinsertnumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jtinsertnumber.setOpaque(false);
        jinsertpanel.add(jtinsertnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 207, 40));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CANTIDAD");
        jinsertpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOMBRE");
        jinsertpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jinsertpanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jbinsertar1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jbinsertar1.setForeground(new java.awt.Color(255, 255, 255));
        jbinsertar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbinsertar1.setText("INSERTAR");
        jbinsertar1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jbinsertar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbinsertar1MouseMoved(evt);
            }
        });
        jbinsertar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbinsertar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbinsertar1MouseExited(evt);
            }
        });
        jinsertpanel.add(jbinsertar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 164, 35));

        fondo.add(jinsertpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 710, 200));

        jtproductos.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jtproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtproductos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        fondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 700, 250));

        jviewpanel.setBackground(new java.awt.Color(217, 32, 36));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LISTADO DE PRODUCTOS");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TIPO");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("NOMBRE");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("MARCA");

        jtviewname.setBackground(new Color(0,0,0,0));
        jtviewname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtviewname.setForeground(new java.awt.Color(255, 255, 255));
        jtviewname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtviewname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jtviewname.setName(""); // NOI18N
        jtviewname.setOpaque(false);
        jtviewname.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtviewnamePropertyChange(evt);
            }
        });

        jtviewmarca.setBackground(new Color(0,0,0,0));
        jtviewmarca.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtviewmarca.setForeground(new java.awt.Color(255, 255, 255));
        jtviewmarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtviewmarca.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jtviewmarca.setName(""); // NOI18N
        jtviewmarca.setOpaque(false);
        jtviewmarca.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtviewmarcaPropertyChange(evt);
            }
        });

        jccategory.setBackground(new Color(0,0,0,0));
        jccategory.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jccategory.setForeground(new java.awt.Color(255, 255, 255));
        jccategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jccategory.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jccategory.setOpaque(false);

        jbviewsearch.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jbviewsearch.setForeground(new java.awt.Color(255, 255, 255));
        jbviewsearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbviewsearch.setText("BUSCAR");
        jbviewsearch.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jbviewsearch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbviewsearchMouseMoved(evt);
            }
        });
        jbviewsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbviewsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbviewsearchMouseExited(evt);
            }
        });

        jbviewlistall.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jbviewlistall.setForeground(new java.awt.Color(255, 255, 255));
        jbviewlistall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbviewlistall.setText("LISTAR TODO");
        jbviewlistall.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jbviewlistall.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbviewlistallMouseMoved(evt);
            }
        });
        jbviewlistall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbviewlistallMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbviewlistallMouseExited(evt);
            }
        });

        jbviewclean.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jbviewclean.setForeground(new java.awt.Color(255, 255, 255));
        jbviewclean.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbviewclean.setText("BORRAR CAMPOS");
        jbviewclean.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jbviewclean.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbviewcleanMouseMoved(evt);
            }
        });
        jbviewclean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbviewcleanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbviewcleanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbviewcleanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jviewpanelLayout = new javax.swing.GroupLayout(jviewpanel);
        jviewpanel.setLayout(jviewpanelLayout);
        jviewpanelLayout.setHorizontalGroup(
            jviewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jviewpanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(198, 198, 198)
                .addComponent(jLabel15)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jviewpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(212, 212, 212))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jviewpanelLayout.createSequentialGroup()
                .addGroup(jviewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jviewpanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jtviewname, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtviewmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jviewpanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jbviewsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jbviewlistall, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jviewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbviewclean, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jccategory, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jviewpanelLayout.setVerticalGroup(
            jviewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jviewpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jviewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jviewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtviewname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtviewmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jccategory, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jviewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbviewsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbviewlistall, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbviewclean, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        fondo.add(jviewpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 710, 0));
        jviewpanel.getAccessibleContext().setAccessibleName("");
        jviewpanel.getAccessibleContext().setAccessibleDescription("");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Close_50px_1.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void clean(){
        int fila = modelo.getRowCount();
        for (int i=1; i<=fila; i++){
            modelo.removeRow(0);
        }
        jtinsertmarca.setText("");
        jtinsertname.setText("");
        jtinsertnumber.setText("");
        jtinsertvent.setText("");
        jtviewmarca.setText("");
        jtviewname.setText("");
        jccategory.setSelectedIndex(0);
        jcinsertkind.setSelectedIndex(0);
    }
    
    public void tableproduct(){
        try {
            String[] columnNames = {"ID", "NOMBRE", "MARCA", "TIPO", "PRECIO DE VENTA","EXISTENCIA"}; // nombre las columnas 
            modelo.setColumnIdentifiers(columnNames); // obtiene los nombres 
            modelo.setColumnCount(6);// crSea las 5 columnas 
            modelo.setRowCount(0);// empienza con la primera fila
            
            jtproductos.setModel(modelo); // muestra el diseño de la tabla
            
            }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "error mostrar" + ex);
        }
    }
    private void jtinsertnamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtinsertnamePropertyChange
        
    }//GEN-LAST:event_jtinsertnamePropertyChange

    private void jbcleanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbcleanMouseMoved
        jbclean.setForeground((Color.black));
    }//GEN-LAST:event_jbcleanMouseMoved

    private void jbcleanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbcleanMouseExited
        jbclean.setOpaque(false);
        jbclean.setForeground(Color.white);
       
    }//GEN-LAST:event_jbcleanMouseExited

    private void jbcleanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbcleanMouseEntered
        jbclean.setOpaque(true);
        jbclean.setBackground(Color.WHITE);
    }//GEN-LAST:event_jbcleanMouseEntered

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        jPanel2.setOpaque(true);
        jPanel2.setBackground(new Color(217,32,36));
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        if(x==200){
            jinsertpanel.setSize(710,200);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i=200; i>=0;i--){
                            Thread.sleep(1);
                             jinsertpanel.setSize(710,i);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }; th.start();
            x=0;
        }else if(x==0){
             jinsertpanel.show();
             jinsertpanel.setSize(710,x);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i=0; i<=x;i++){
                            Thread.sleep(1);
                             jinsertpanel.setSize(710,i);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }; th.start();
            x=200;
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        if(y==200){
            jviewpanel.setSize(710,200);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i=200; i>=0;i--){
                            Thread.sleep(1);
                            jviewpanel.setSize(710,i);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }; th.start();
            y=0;
        }else if(y==0){
             jviewpanel.show();
             jviewpanel.setSize(710,y);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i=0; i<=y;i++){
                            Thread.sleep(1);
                             jviewpanel.setSize(710,i);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }; th.start();
            y=200;
        }
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setOpaque(true);
        jPanel5.setBackground(new Color(217,32,36));
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setOpaque(false);
        jPanel5.setBackground(new Color(151,17,21));
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        jPanel2.setOpaque(false);
        jPanel2.setBackground(new Color(151,17,21));
    }//GEN-LAST:event_jPanel2MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.dispose();
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        clean();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setOpaque(true);
        jPanel6.setBackground(new Color(217,32,36));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        jPanel6.setOpaque(false);
        jPanel6.setBackground(new Color(151,17,21));
    }//GEN-LAST:event_jPanel6MouseExited

    private void jtviewnamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtviewnamePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jtviewnamePropertyChange

    private void jtviewmarcaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtviewmarcaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jtviewmarcaPropertyChange

    private void jbviewsearchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbviewsearchMouseMoved
        jbviewsearch.setForeground((Color.black));
    }//GEN-LAST:event_jbviewsearchMouseMoved

    private void jbviewsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbviewsearchMouseEntered
        jbviewsearch.setOpaque(true);
        jbviewsearch.setBackground(Color.WHITE);
    }//GEN-LAST:event_jbviewsearchMouseEntered

    private void jbviewsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbviewsearchMouseExited
        jbviewsearch.setOpaque(false);
        jbviewsearch.setForeground(Color.white);
    }//GEN-LAST:event_jbviewsearchMouseExited

    private void jbviewlistallMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbviewlistallMouseMoved
        jbviewlistall.setForeground((Color.black));
    }//GEN-LAST:event_jbviewlistallMouseMoved

    private void jbviewlistallMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbviewlistallMouseEntered
        jbviewlistall.setOpaque(true);
        jbviewlistall.setBackground(Color.WHITE);
    }//GEN-LAST:event_jbviewlistallMouseEntered

    private void jbviewlistallMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbviewlistallMouseExited
        jbviewlistall.setOpaque(false);
        jbviewlistall.setForeground(Color.white);
    }//GEN-LAST:event_jbviewlistallMouseExited

    private void jbviewcleanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbviewcleanMouseMoved
        jbviewclean.setForeground((Color.black));
    }//GEN-LAST:event_jbviewcleanMouseMoved

    private void jbviewcleanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbviewcleanMouseEntered
        jbviewclean.setOpaque(true);
        jbviewclean.setBackground(Color.WHITE);
    }//GEN-LAST:event_jbviewcleanMouseEntered

    private void jbviewcleanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbviewcleanMouseExited
        jbviewclean.setOpaque(false);
        jbviewclean.setForeground(Color.white);
    }//GEN-LAST:event_jbviewcleanMouseExited

    private void jbinsertar1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbinsertar1MouseMoved
        jbinsertar1.setForeground((Color.black));
    }//GEN-LAST:event_jbinsertar1MouseMoved

    private void jbinsertar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbinsertar1MouseEntered
        jbinsertar1.setOpaque(true);
        jbinsertar1.setBackground(Color.WHITE);
    }//GEN-LAST:event_jbinsertar1MouseEntered

    private void jbinsertar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbinsertar1MouseExited
        jbinsertar1.setOpaque(false);
        jbinsertar1.setForeground(Color.white);
    }//GEN-LAST:event_jbinsertar1MouseExited

    private void jbcleanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbcleanMouseClicked
        clean();
    }//GEN-LAST:event_jbcleanMouseClicked

    private void jbviewcleanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbviewcleanMouseClicked
        clean();
    }//GEN-LAST:event_jbviewcleanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jbclean;
    private javax.swing.JLabel jbinsertar1;
    private javax.swing.JLabel jbviewclean;
    private javax.swing.JLabel jbviewlistall;
    private javax.swing.JLabel jbviewsearch;
    private javax.swing.JComboBox<String> jccategory;
    private javax.swing.JComboBox<String> jcinsertkind;
    private javax.swing.JPanel jinsertpanel;
    private javax.swing.JTextField jtinsertmarca;
    private javax.swing.JTextField jtinsertname;
    private javax.swing.JTextField jtinsertnumber;
    private javax.swing.JTextField jtinsertvent;
    private javax.swing.JTable jtproductos;
    private javax.swing.JTextField jtviewmarca;
    private javax.swing.JTextField jtviewname;
    private javax.swing.JPanel jviewpanel;
    // End of variables declaration//GEN-END:variables
}
